// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://cvnaihsujkvduzzyjbzn.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bmFpaHN1amt2ZHV6enlqYnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE3MjI5OTMsImV4cCI6MjA0NzI5ODk5M30.kxQcD2k-l-AVjHx2iumS0_cglNskJ39UVp1qWhwVO0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);